- name: Configure the webservers
  hosts: webservers
  become: yes
  tasks:
    - name: Create a non-root user
      user:
        name: vparekh
        state: present

    - name: Install nginx
      package:
        name: nginx
        state: present

- name: Configure the database
  hosts: databases
  become: yes
  tasks:
    - name: Install MySQL Server
      package:
        name: mysql-server
        state: present
