- name: Configure the webservers
  hosts: webservers
  become: yes
  roles:
    - users
  tasks:
    # - name: Create a non-root user
    #   user:
    #     name: stark
    #     state: present

    - name: Install Nginx
      package:
        name: nginx
        state: present
