- name: Build wordpress image
  shell:
    chdir: ~/wordpress-lemp-docker
    cmd: docker-compose build "{{ service_name }}"
  
- name: Start wordpress container
  shell:
    chdir: ~/wordpress-lemp-docker
    cmd: docker-compose up -d --no-deps --build "{{ service_name }}"